# tag it as build
FROM oven/bun AS build 

WORKDIR /my-project

COPY bun.lockb .
COPY package.json .

RUN bun install --frozen-lockfile

COPY src ./src

# compile everything to a binary called cli which includes the bun runtime
RUN bun build ./src/index.ts --compile --outfile cli

# use a smaller image without bun
FROM ubuntu:22.04 

WORKDIR /my-project

# copy the compiled binary from the build image
COPY --from=build /my-project/cli /my-project/cli

# execute the binary!
CMD ["/my-project/cli"]

# ---
# source: https://dev.to/code42cate/how-to-dockerize-a-bun-app-38e4