
services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sh -c "bun run build && bun run start"
    expose:
      - 3000
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file:
      - ./.env.prod
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    hostname: nginx
    env_file:
      - ./.env.prod
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    restart: unless-stopped