
services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: bun run dev
    volumes:
      - ./app:/my-project/app
      - ./components:/my-project/components
      - ./data:/my-project/data
      - ./lib:/my-project/lib
      - ./src:/my-project/src
      - ./content:/my-project/content
    expose:
      - 3000
    environment:
      NODE_ENV: development
    env_file:
      - ./.env
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    hostname: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    env_file:
      - ./.env
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    restart: unless-stopped